### ISSUE TITLE
Genesis Keys for Testnet

### ISSUE THREAD

**Issue by adrianbrink** [anoma/anoma#1004]
Collect all persistent keys here and add them to the genesis file on every testnet launch.

**Comment by cwgoes** [comment]
@juped what command(s) should users run to generate the keys we need here (implicit account and possibly Tendermint pubkey?)

**Comment by tzemanovic** [comment]
> @juped what command(s) should users run to generate the keys we need here (implicit account and possibly Tendermint pubkey?)

we have `anomac utils init-validator` for this, but it needs some updates (see https://github.com/anoma/anoma/issues/997)

**Comment by tzemanovic** [comment]
this has been done via https://github.com/heliaxdev/anoma-network-config and the private counter-part
