### ISSUE TITLE
Implement queuing of wETH transfers in the native validity predicate for the Namada-Ethereum bridge

### ISSUE THREAD

**Issue by james-chf** [anoma/anoma#1059]
Validators must listen for events emitted on the Ethereum blockchain by our bridge smart contract, which will include transfer events (something like `transfer_to_namada(ERC20 Ethereum address, amount, Namada receiver address, minimum number of confirmations)`). Validators include Ethereum block state onto the Namada blockchain.

Once the Ethereum block containing these transfer events is recognized as "seen" on the Namada chain in block `n`, then for block `n+1` the proposer must make a protocol transaction to do the following

- enqueue `TransferFromEthereum` messages to `@vp_eth_bridge/queue` for each transfer event in the seen block
- for each `TransferFromEthereum` message in `@vp_eth_bridge/queue`, if the minimum number of confirmations has been reached, dequeue the message and mint wETH for the receiver of the transfer on Namada (#1064)

`vp_eth_bridge` will be triggered in block `n+1` due to the changes to one of its keys (`@vp_eth_bridge/queue`), it must validate that messages were processed correctly by the protocol transaction.

See https://specs.anoma.net/master/architecture/namada/ethereum-bridge.html#minting-wrapped-eth-tokens-on-namada for latest spec.

### PRs
- [ ] EthBridge internal address that rejects all txs (#1066)
- [ ] EthBridge VP should accept txs made by the protocol to the `/queue` key
- [ ] implement protocol tx (`tx_eth_bridge`) that can add `TransferFromEthereum` messages to the `/queue`
- [ ] EthBridge VP should validate changes to its `/queue` (e.g. ensure only `TransferFromEthereum` messages are added, etc.) based on the latest changes to Ethereum state included in the last block

**Comment by batconjurer** [comment]
This VP should only be triggered when a protocol tx is sent by the validators who see that an event has the required number of confirmations. This won't be triggered every time the ethereum state is updated ( I think the spec may say the same as here, but that was a confusion on my part about chaining together vps).

**Comment by james-chf** [comment]
This issue will be replaced by new one(s) based on the updated Ethereum bridge spec
