### ISSUE TITLE
Hosted docs are not public

### ISSUE THREAD

**Issue by ruuda** [anoma/anoma#1089]
In the readme, there is a “docs” link that points to https://docs.anoma.network/master/:

https://github.com/anoma/anoma/blob/e64b03c89a2bb408b9132cdf2c648cf6d0e659bf/README.md?plain=1#L14

This url redirects to https://app.gitbook.com/s/-MjE1HB6l7e7zGXtCrd-/master, which shows a login page:

![anoma-docs-gitboot-sign-in](https://user-images.githubusercontent.com/506953/167136203-6044cdd2-783a-4589-8776-b5736aaf27c3.png)

**Comment by tzemanovic** [comment]
Thank you for opening the issue! The docs from anoma/anoma are being migrated to https://dev.anoma.net (to be updated by #1082 once finished), but you can find the new user docs at https://docs.anoma.net.
