### ISSUE TITLE
sccache timeouts in CI

### ISSUE THREAD

**Issue by james-chf** [anoma/anoma#1204]
eg https://ci.heliax.dev/anoma/anoma/4214/3/4

```
+ sccache --start-server
sccache: Starting the server...
sccache: error: Timed out waiting for server startup
```

This only happens occasionally. We could probably workaround by allowing more time for sccache to start up.

**Comment by tzemanovic** [comment]
I’ve also been getting these quite often

**Comment by tzemanovic** [comment]
cache cleared, should be good for now
