### ISSUE TITLE
Could not compile dependency :rocksdb

### ISSUE THREAD

**Issue by hui-an-yang** [anoma/anoma#1412]
I am having trouble with installation on macbook m1 
At first, I encountered "Could not compile dependency :enacl" which made me `git checkout mariari/no-libsodium`
And now at `mix compile` command I see the error messages below

> ** (Mix) Could not compile dependency :rocksdb, "/Users/huianyang/.mix/elixir/1-17/rebar3 bare compile --paths /Users/huianyang/Playground/anoma/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile rocksdb --force", update it with "mix deps.update rocksdb" or clean it with "mix deps.clean rocksdb"

Am hoping people had similar issues can help out

**Comment by agureev** [comment]
@hui-an-yang Hello! Is the error still present? I assume you have tried to clean and re-get as described?

**Comment by hui-an-yang** [comment]
hello @agureev, after updating to Anoma 0.25.0 and following the updated README.md has been able to compile successfully now, ty.
