### ISSUE TITLE
Cairo errors not handled during the verification of shielded transactions

### ISSUE THREAD

**Issue by karbyshev** [anoma/anoma#1425]
During the verification of shielded partial transaction, each individual proof record is validated using `Cairo.verify/1` function.
The results of these verifications are then combined using `&&` operator. However, this approach is flawed, as the `&&` operator interprets non-nil arguments as true. For example,

```elixir
iex(13)> true && {:error, 1} && true
true
```

customer:
performer:
deadline:
estimated:
started:
actual:
completed:
confirmed:
dependencies:
- [ ]
supersedes:
-
---

<definition of done>

**Comment by karbyshev** [comment]
Fixed in #1418

**Comment by XuyangSong** [comment]
merged in v 0.28
