### ISSUE TITLE
Change Commitment Storage

### ISSUE THREAD

**Issue by agureev** [anoma/anoma#1566]
customer: @mariari 
performer:
deadline:
estimated:
started:
actual:
completed:
confirmed:
dependencies:
- [ ] #1454 
supersedes:
-
---

Currently the TRM gathers all commitments into a commitment set. After we get proper API for dealing with commitment trees, we should replace this by just commitment tree storage.

**Comment by mariari** [comment]
Working with @juped and @murisi
