### ISSUE TITLE
Make All Tests Asynchronous

### ISSUE THREAD

**Issue by agureev** [anoma/anoma#1593]
customer: @mariari 
performer:
deadline:
estimated:
started:
actual:
completed:
confirmed:
dependencies:
- [ ]
supersedes:
-
---

We do not have tests which assume synchronicity. We should try to make everything run async. However currently if we make all tests async in the Node, e.g. we encounter the following ETS errors:

`* 1st argument: the table identifier refers to an ETS table with insufficient access rights`

which can be fixed by making the initialization public rather than protected for the table, yet that then spawn another error regarding inserting non-existent tables. 

@m1dnight you probably are the best person to tackle this

**Comment by m1dnight** [comment]
The anoma_node application has been addressed here: https://github.com/anoma/anoma/pull/1602

I'm looking at making the other applications concurrent  as well, but those will take some time :)
