### ISSUE TITLE
add get_intent env function

### ISSUE THREAD

**Issue by sribst** [anoma/anoma#215]
the matchmaker maintains a state that could grow a lot.
it can be interesting for it to have a function allowing to read from the intent mempool of the host. This would reduce the state size and duplication of information.

The signature could be : `get_intent(intent_id:Vec<u8>) -> Vec<u8>`

link to #204

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762876376131) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
the matchmaker is no longer in wasm, so I think we can close this
