### ISSUE TITLE
Protocol parameters - epochs

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#331]
Various components (e.g. PoS and DKG) rely on a notion of epochs. We should decide if we want to measure these in a number of blocks or time. Epochs should be uniquely identified by consecutive integers.

In the base ledger, the duration should be set in a protocol parameter that is written to and read from storage to allow for changes. Any changes to protocol parameters could be applied by validators and switched on 2/3 voting power consensus. This could be implemented as a native validity predicate.

**Comment by cwgoes** [comment]
For now we should have an epoch which ends as soon as both a minimum time and minimum number of blocks have passed.

(this will be the same as the unbonding period logic, though the constants will be different)
