### ISSUE TITLE
incentive mechanism

### ISSUE THREAD

**Issue by sribst** [anoma/anoma#37]
The initial page is at `tech-specs/src/explore/design/gossip/incentive.md`

Inspiration reading :

* [On Bitcoin and Red Balloons](https://arxiv.org/abs/1111.2626)

To describe : 

* [ ] incentive function 
* [ ] TODO

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762903989987) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Closing in favour of more recent issues.
