### ISSUE TITLE
Email sender shows the email coming from "Anome Network"

### ISSUE THREAD

**Issue by sean-magin** [anoma/anoma#374]
<img width="246" alt="Screen Shot 2021-07-30 at 10 48 03 PM" src="https://user-images.githubusercontent.com/14209806/127642530-f5a4e2d8-fa43-43ee-9c7b-a7e94e11f029.png">

Expected:
Should show it's coming from "Anoma Network"

**Comment by tzemanovic** [comment]
Noted, thank you for the heads-up!
