### ISSUE TITLE
Support encrypted transactions

### ISSUE THREAD

**Issue by batconjurer** [anoma/anoma#392]
At present, we only have defined unencrypted transactions. Encrypted transactions will be a new type that will wrap these and contain extra data such as fees, gas limits, and signatures. We need to do the following

 - [x]  Add in the new type / proto definitions of encrypted transactions
 - [x] Add the validation of encrypted transactions, which differs from the validation on the wrapped transaction
 - [x] Change our storage logic to always include validated encrypted transactions regardless of the validity of the wrapped transaction
 - [x] Make a custom event that indicates the success value of applying a transaction after it is decrypted.
 - [x] Make a final decision regarding the policy of how to ensure gas limits for blocks are not exceeded and document this appropriately in the tech specs
 - [x] Cover with tests

**Comment by cwgoes** [comment]
Note that all transactions should be encrypted (once this feature is supported).
