### ISSUE TITLE
[Ledger][design] front-running protection

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#42]
The initial page is at `tech-specs/src/explore/design/ledger/front-running.md`

To describe:

* [ ] DKG protocol steps for front-running protection
* [ ] DKG and tendermint (ABCI++?)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762908173502) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Closing in favour of more updated issues.
