### ISSUE TITLE
[Ledger][design] validity predicates

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#44]
The initial page is at `tech-specs/src/explore/design/ledger/vp.md`

To describe:

* [x] possible implementations
* [x] how are the transactions, the state storage and state updates to be validated presented to VPs?
* [ ] gas accounting?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762963653793) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Closing in favour of more recent issues.
