### ISSUE TITLE
[Ledger][design] accounts

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#45]
The initial page is at `tech-specs/src/explore/design/ledger/accounts.md`

To describe:

* [x] account types
* [x] accounts data
* [x] accounts addresses (should we use public key hashes?)
* [ ] accounts life-cycle (how is an account created on chain, is it deleted when its balance is empty?)
* [ ] storage fees

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762964787292) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Closing in favour of more recent issues.
