### ISSUE TITLE
automated Tendermint installation

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#450]
Add a script and command for automated tendermint installation, maybe with a check that tendermint is not already installed and also checking its `tendermint version`. This could then be part of `make install`

**Comment by tzemanovic** [comment]
In the ledger, we should also allow to specify path to tendermint via an env variable (with the default of using the one from `$PATH`)

**Comment by tzemanovic** [comment]
There used to be shell scripts for installation in tendermint repo, but they got removed in https://github.com/tendermint/tendermint/pull/4242. All the scripts except for osx build from source though, so it would be better to write ones that installs it from the tendermint releases instead. Maybe we could detect the platform and have only a single install script too.

**Comment by atoz7** [comment]
hello,
ok, i'll take a look.
 
 imho. at least the following things should be met:
 * check for tendermint-executable within the existing path (and also check for a suitable version)
 * install from binary-release, not from source (select suitable release regarding to OS/architecture)
 * select either a specific version or the latest patch-level from the 0.34.x release
 * install it to the common application-path of the anoma-utilities

br,
joachim

**Comment by atoz7** [comment]
hello,

after thinking about this for a little while.

this shouldn't be too hard if i am able to assume, that we use some kind of a "posix-compliant" environment, e.g.
* sh or even bash available
* several utils, which come in handy to detect the system, the architecture of an ongoing build
for example: at least "uname", "curl" or even "read"
* neccessary tools to extract the archive
in tendermints case "tar" and "gzip"

but for me its atm not clear, what kind of build-environments we want to support and what i can safely assume as being present in such a build-environment.

additionally i think such an approach should only be used as an interim-solution for ongoing development.

in the long run / for productive use we should decide on which kind of packages we want to provide and how to handle such dependencies in a sane way - either as an external dependency or an integrated part of our package(s).

br,
joachim

**Comment by tzemanovic** [comment]
@atoz7 thank you for the write up!

> this shouldn't be too hard if i am able to assume, that we use some kind of a "posix-compliant" environment, e.g. ...

I think this is fine to assume

> but for me its atm not clear, what kind of build-environments we want to support and what i can safely assume as being present in such a build-environment.

I think we could just follow the platforms that are available from tendermint releases. This should need any other dependency than the simply tools for download and installation

> in the long run / for productive use we should decide on which kind of packages we want to provide and how to handle such dependencies in a sane way - either as an external dependency or an integrated part of our package(s).

I agree, it's mostly to automate this manual process so it's to get this up and running from scratch. I think for pre-built binaries we can optionally ship with tendermint included.

**Comment by atoz7** [comment]
hello,

i've added lets call it a "first shot" of a script for the automatic tendermint-installation to the following branch / its clearly open for discussion :)
* https://github.com/anoma/anoma/tree/development/script_tendermint_installation

i have to admit, that i'm not really happy with this solution, but this somehow reflects the situation:

* it hardcodes major/minor-version to "0.34"
* it hardcodes patch-level to "13"
* it uses "uname" to somehow detect the system / architecture it runs on
* it hardcodes to target "/usr/local/bin", which should be in someones PATH

on the one hand, the target-path is controlled by cargo itself and not within the Makefile. it doesn't get explicitly set for calls to cargo from the Makefile - for example via the --root parameter -, so i'm not able to detect it properly on this level. yes, it'll resolves to $HOME/.cargo/bin in most cases, but additionally this is a location where i don't want to copy 3rd-party components to.

on the other hand, regarding the system/architecture-detection: we try to use make as a build tool to handle 3rd-party software dependencies, but without the proper complementary tools to do this right - keyword automake/-conf for build-configuration -, which would make live a lot easier.

br,
joachim

**Comment by tzemanovic** [comment]
> hello,
> 
> i've added lets call it a "first shot" of a script for the automatic tendermint-installation to the following branch / its clearly open for discussion :)
> 
>     * https://github.com/anoma/anoma/tree/development/script_tendermint_installation
> 
> 
> i have to admit, that i'm not really happy with this solution, but this somehow reflects the situation:
> 
>     * it hardcodes major/minor-version to "0.34"
> 
>     * it hardcodes patch-level to "13"
> 
>     * it uses "uname" to somehow detect the system / architecture it runs on
> 
>     * it hardcodes to target "/usr/local/bin", which should be in someones PATH
> 
> 
> on the one hand, the target-path is controlled by cargo itself and not within the Makefile. it doesn't get explicitly set for calls to cargo from the Makefile - for example via the --root parameter -, so i'm not able to detect it properly on this level. yes, it'll resolves to $HOME/.cargo/bin in most cases, but additionally this is a location where i don't want to copy 3rd-party components to.
> 
> on the other hand, regarding the system/architecture-detection: we try to use make as a build tool to handle 3rd-party software dependencies, but without the proper complementary tools to do this right - keyword automake/-conf for build-configuration -, which would make live a lot easier.
> 
> br,
> joachim

Thank you Joachim, this looks good for a starter, but I'm getting some errors trying to run it. I've opened #490 to discus.
