### ISSUE TITLE
build fails on a ARM64 / aarch64 based debian 11/bullseye gnu/linux system

### ISSUE THREAD

**Issue by atoz7** [anoma/anoma#474]
hello,

out of curiosity i tried to compile the master-branch of anoma on a system based on the latest debian version 11/bullseye port for the ARM64/aarch64 architecture (hardware: raspberry pi4):

2 errors occured during the compilation

during the "make build-wasm-scripts-docker" step
 wasm-opt fails with
> make[1]: Entering directory '/usr/local/rust/wasm'
> /bin/sh: 1: wasm-opt: Exec format error
> [...]

(a few more similar errors, see attached files)

[make_wasm_script_docker.txt](https://github.com/anoma/anoma/files/7185815/make_wasm_script_docker.txt)

and during the "make" step
 wasmer-compiler-singlepass fails to compile properly

> error: Unknown instruction mnemonic 'xor'
>   --> /home/adi/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.0.0/src/emitter_x64.rs:709:28
> [...]

(folowed by lots of other errors related to this cargo-module, see attached files)

[build_error_make.txt](https://github.com/anoma/anoma/files/7185791/build_error_make.txt)

br,
joachim

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763115461973) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
not sure if this is still relevant
