### ISSUE TITLE
CI run in a PR branch - don't try to merge

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#482]
Currently, the CI that runs in a PR attempts to merge the PR branch in master. This means that if auto-merge fails, the CI will fail too. In some cases auto-merge can also produce a wrong commit in `push-wasm` step, as is a case in this run https://ci.heliax.dev/anoma/anoma/1246/3/6, in which the PR branch was behind master (missing latest merge from master, which also modified WASMs), which created conflicts in the re-built WASMs that then didn't get updated (only the WASMs without conflicts got updated).

It would be preferable not to do this and just run with the branch as is. For this, we will need to update/change how we do the scripts integrity check, which currently only allows using the latest hash values.

**Comment by Fraccaman** [comment]
Done.
