### ISSUE TITLE
What to do/add in the CI

### ISSUE THREAD

**Issue by sribst** [anoma/anoma#57]
It would be nice to have a CI ! 
Lets use this issue to report all stuff we want the CI to check

**Comment by batconjurer** [comment]
I would propose running clippy with the --all-targets flags. I like nicely formatted unit tests too :smile: I ran it on master and caught only a few minor things (overzealous cloning!). So it should be a simple add.

**Comment by Fraccaman** [comment]
I think it would be a good idea!
