### ISSUE TITLE
rocksdb uses too many files

### ISSUE THREAD

**Issue by juped** [anoma/anoma#582]
The default for rocksdb is to open an unlimited number of files (this is the performance option), which runs into problems with default ulimits which are more like 1024. There are two approaches we could take:

* configure rocksdb to use ~1000 open files. this makes the performance a bit worse since rocksdb then needs a data structure to keep track of which files it has open.
* set our resource limits a bit higher. this allows us to use the high performance option. we can set it to something pretty high

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762975350567) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
I think this has been solved by #590
