### ISSUE TITLE
anoman pegs one cpu core at 100%

### ISSUE THREAD

**Issue by juped** [anoma/anoma#592]
this behavior is somewhat odd - is it spinning somewhere? seen on a few machines

**Comment by tzemanovic** [comment]
#609 fixes `anoma` cpu hogging, `anoman` looks okay for me, but as @SimSaladin pointed out, it uses surprisingly high number of threads

**Comment by tzemanovic** [comment]
This should be fixed by #609. Pls re-open if not.
