### ISSUE TITLE
User guide section link in README gives a 404 error

### ISSUE THREAD

**Issue by sean-magin** [anoma/anoma#605]
![Screen Shot 2021-11-02 at 10 33 08 PM](https://user-images.githubusercontent.com/14209806/139821710-45298286-a2df-42ba-bdec-87851a937da8.png)
 
 When clicking on this link in the README it leads to a 404 at this link: https://docs.anoma.network/user-guide/
 
![Screen Shot 2021-11-02 at 10 31 27 PM](https://user-images.githubusercontent.com/14209806/139821752-94dfc569-24af-4511-b4f6-e4a6ecfc6101.png)

**Comment by tzemanovic** [comment]
Thanks for the report and sorry for the broken link! The user guide for the current release version is at https://docs.anoma.network/v0.2.0/user-guide/

**Comment by sean-magin** [comment]
Yup all good I ended up finding it. Thanks for the quick response @tzemanovic 🙏
