### ISSUE TITLE
Make install failing due to "feature `resolver` being required"

### ISSUE THREAD

**Issue by sean-magin** [anoma/anoma#606]
Thank you for the bug report. Please provide any information that may be relevant to the issue you're experiencing.

After cloning the anoma repo whenever I run `make install` I'm getting this error: 

![Screen Shot 2021-11-02 at 10 48 11 PM](https://user-images.githubusercontent.com/14209806/139824240-fe80d26c-4337-4de0-9148-298e1d5bb1ed.png)

I've attempted to add the recommended line (cargo-features = ["resolver"]) to cargo.toml file but no dice 🤷

**Comment by tzemanovic** [comment]
It looks like you're using some older version of cargo. If you're using rustup, can you pls try to `rustup update` first?

**Comment by tzemanovic** [comment]
I'm not sure why it's not being picked up from the rust-toolchain.toml, perhaps the older version doesn't support `.toml` format, which afaik has been added later. From rust 1.56 on, we'll also be able to add the `rust-version` version in Cargo.toml (<https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-rust-version-field>).

**Comment by sean-magin** [comment]
Yup, `rustup update` did the trick! Thank you :D
