### ISSUE TITLE
Make elements in  "Participate in the Anoma Network" section of the website clickable

### ISSUE THREAD

**Issue by AMiles14** [anoma/anoma#651]
The elements in the ["Participate in the Anoma Network"](https://anoma.network/community) seem to be clickable but don't direct anywhere. Since we have started writing the "Agents of Anoma" I think we can begin to link the articles to correlating role. Ex. The description/element of a "validator" can be directed to the new [Validators article](https://anoma.network/blog/agents-of-anoma-validators). @claraishere @pablohildo @celsobonutti

**Comment by claraishere** [comment]
Yes, we prepared them in order to just update the link when we get more information about every role :)
Is there anything you need from the design part?

**Comment by AMiles14** [comment]
I think the design part is fine! we should just update them as the articles come out :)

**Comment by pablohildo** [comment]
Noted! I will update this one soon and make sure we remember updating the others whenever a new article is ready

**Comment by celsobonutti** [comment]
Hey @AMiles14, a minor comment: issues related to anoma.network should be created in the [anoma.network](github.com/heliaxdev/anoma.network) repo.
