### ISSUE TITLE
Feigenbaum-1

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#680]
For the next testnet:

* #631 
* #157 and #677
* #372 
* #81 
* #678 
* #711
* #712
* cont. stability testing and profiling

Nice to haves:

* #193 
* #674
* #675

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763318784558) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Closing this as no longer relevant.
