### ISSUE TITLE
TxQueue should be persisted in local storage rather than separate file

### ISSUE THREAD

**Issue by batconjurer** [anoma/anoma#711]
The TxQueue is an essential part of a validator's local state. This queue is a global cache that can be overwritten every block. Currently it is persisted in  special file when the Shell is dropped from scope. On bootup, this file is needed to resume. However, in some cases, this file may not exist, e.g. on out-of-memory crashes. This locks validators out of restarting and forces them to replay from scratch.

Because it is crucial that the tx queue be in sync with the last persisted block, we should maintain a global tx queue in our storage and when persisting state, atomically commit both the block and the new queue.

The atomic commits also relates to #372

**Comment by tzemanovic** [comment]
for state rollback (#663), let's also write a predecessor value of the tx_queue
