### ISSUE TITLE
Error when trying to generate wallet key

### ISSUE THREAD

**Issue by alexpashkov** [anoma/anoma#744]
After installing Anoma I'm trying to generate the wallet key and getting an error:
```
$ anoma wallet key gen --alias my-key
Tried to read config in .anoma but failed with: Error while deserializing config: missing field `tendermint_mode`
```
I'm on Ubuntu 20.04 and I've followed the steps here: https://docs.anoma.network/v0.3.0/user-guide/install.html and I've also ran
`anoma client utils join-network --chain-id=anoma-feigenbaum-0.ebb9e9f9013` to join the public testnet

**Comment by Fraccaman** [comment]
Hi @alexpashkov! Thanks for trying out Anoma :)
This error probably means that you are using a wrong version of tendermint. Could you please check that you have installed tendermint version 0.34.x?

**Comment by alexpashkov** [comment]
Sure:
```
$ tendermint version
0.34.13
```

**Comment by IvanMMM** [comment]
Same here
My config is really missing `tendermint_mode` field
`tendermint` version is same as user above
```
$ tendermint version
0.34.13
```

**Comment by Fraccaman** [comment]
So, basically the `anoma-feigenbaum-0.ebb9e9f9013` configurations are incompatible with the new v0.3.0 release. Also `anoma-feigenbaum-0.ebb9e9f9013` has been shut down, so there is no point in joining :(
