### ISSUE TITLE
Ledger does a dirty shutdown on SIGTERM since 0.3.0

### ISSUE THREAD

**Issue by SimSaladin** [anoma/anoma#768]
Since 0.3.0, ledger state always gets corrupted when the `anoman` process is killed with `SIGTERM` (which is the default signal e.g. systemd sends to stop a service). To start the node again after `SIGTERM` it's necessary to reset the state - a panic occurs at startup otherwise.

Using `SIGINT` instead (e.g. what CTRL-C does) does do a clean shutdown, so I've been using that as a workaround with systemd (`KillSignal=SIGINT` in the service definition).

`SIGTERM` used to do a clean shutdown in 0.2.0. It would be nice to get back that behavior, since it is what is expected per POSIX.

**Comment by tzemanovic** [comment]
What's the panic at startup if you use `SIGTERM`? Is it the missing tx queue file?

**Comment by SimSaladin** [comment]
Mysteriously I can't reproduce the crash anymore. Luckily Loki still has logs from when `SIGTERM` was still used on the testnet validators. This is from 24.12.:

![2022-01-04-161742_1365x322_scrot](https://user-images.githubusercontent.com/532435/148081915-7e143325-3740-4d35-ab78-c5d243ddbbc6.png)

It's indeed the missing tx queue file.

**Comment by SimSaladin** [comment]
Possibly related, this is what happens when `anoman` gets `SIGTERM` when it just recently started syncing the chain:

```
E[2022-01-04|15:36:28.252] Stopping abci.socketClient for error: read message: EOF module=abci-client connection=mempool
I[2022-01-04|15:36:28.252] Stopping socketClient service                module=abci-client connection=mempool impl=socketClient
E[2022-01-04|15:36:28.252] mempool connection terminated. Did the application crash? Please restart tendermint module=proxy err="read message: EOF"
E[2022-01-04|15:36:28.253] Stopping abci.socketClient for error: read message: EOF module=abci-client connection=consensus
I[2022-01-04|15:36:28.253] Stopping socketClient service                module=abci-client connection=consensus impl=socketClient
Terminated
E[2022-01-04|15:36:28.253] error in proxyAppConn.EndBlock               module=state err="read message: EOF"

panic: Failed to process committed block (444:6B813EC7C984A6FFC6ABED78634783D69C92A722B931510680BF2743959770EE): read message: EOF

goroutine 5401 [running]:github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000230700, 0x0)
        github.com/tendermint/tendermint/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint/blockchain/v0/reactor.go:110 +0x8c
```

It still starts fine again after that, but the sync restarts from the first block instead of where it left off. Meanwhile `SIGINT` does not produce any errors and sync continues from the block where it left off.

**Comment by tzemanovic** [comment]
the missing tx queue file will be fixed by #728, but I'm not sure about the other issue. Did anything panic in rust too?

**Comment by SimSaladin** [comment]
No, all output after the signal was in my previous comment. Comparing that output to the output after `SIGINT`:

```
Jan 04 15:45:23.098  INFO anoma_apps::node::ledger: Received interrupt signal, exiting...
Jan 04 15:45:23.098  INFO anoma_apps::node::ledger::tendermint_node: Shutting down Tendermint node...
Jan 04 15:45:23.102  INFO anoma_apps::node::ledger: Tendermint node is no longer running.
Jan 04 15:45:23.102  INFO anoma_apps::node::ledger::shell: Storing a transaction queue...
Jan 04 15:45:23.102  INFO anoma_apps::node::ledger::shell: Transaction queue has been stored.
Jan 04 15:45:23.102  INFO anoma_apps::node::ledger: Anoma ledger node has shut down.
```

It looks like the signals are handled differently: on `SIGINT` the ledger gracefully shuts down tendermint, stores the tx queue and finally shuts down itself, but on `SIGTERM` it just terminates itself immediately, without storing the tx queue, and tendermint dies shortly after because of `EOF` on the ABCI socket.

I think that the termination signal should trigger the same shutdown procedure as the interrupt signal does. Do you agree?

**Comment by tzemanovic** [comment]
> No, all output after the signal was in my previous comment. Comparing that output to the output after `SIGINT`:
> 
> ```
> Jan 04 15:45:23.098  INFO anoma_apps::node::ledger: Received interrupt signal, exiting...
> Jan 04 15:45:23.098  INFO anoma_apps::node::ledger::tendermint_node: Shutting down Tendermint node...
> Jan 04 15:45:23.102  INFO anoma_apps::node::ledger: Tendermint node is no longer running.
> Jan 04 15:45:23.102  INFO anoma_apps::node::ledger::shell: Storing a transaction queue...
> Jan 04 15:45:23.102  INFO anoma_apps::node::ledger::shell: Transaction queue has been stored.
> Jan 04 15:45:23.102  INFO anoma_apps::node::ledger: Anoma ledger node has shut down.
> ```
> 
> It looks like the signals are handled differently: on `SIGINT` the ledger gracefully shuts down tendermint, stores the tx queue and finally shuts down itself, but on `SIGTERM` it just terminates itself immediately, without storing the tx queue, and tendermint dies shortly after because of `EOF` on the ABCI socket.
> 
> I think that the termination signal should trigger the same shutdown procedure as the interrupt signal does. Do you agree?

I see thanks and agree that would be a lot better!

**Comment by tzemanovic** [comment]
we can use https://docs.rs/tokio/latest/tokio/signal/unix/fn.signal.html to handle the termination signal
