### ISSUE TITLE
set optional WASM sha256 hashes in network source config

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#777]
the hashes don't need to be set in the source config, because the `anomac utils init-network` command will fill them in from the given `--wasm-checksums-path`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762984814146) by [Unito](https://www.unito.io)

**Comment by GGiecold** [comment]
Issue addressed by https://github.com/anoma/anoma/pull/845
