### ISSUE TITLE
Cache storage sub-space

### ISSUE THREAD

**Issue by yito88** [anoma/anoma#81]
The current storage store all accounts' subspaces in the memory.
https://github.com/heliaxdev/anoma-prototype/blob/e84bd322a2b8c62b630c9e31e3fdc7059f852478/ledger/src/bin/anoma-node/shell/storage/mod.rs#L53

We want to support many accounts, even if the total size of subspaces is over the memory, by caching subspaces.
When the latest state isn't cached, we can get the state from the DB (the blocks).

**Comment by tzemanovic** [comment]
done in #683, merged via #721
