### ISSUE TITLE
ci: create-release on tag fails

### ISSUE THREAD

**Issue by juped** [anoma/anoma#846]
ex: https://ci.heliax.dev/anoma/anoma/2798/1/6

I don't know why, because there's not very informative output.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762705857877) by [Unito](https://www.unito.io)

**Comment by Fraccaman** [comment]
it was due to `gh` complaining about GITHUB_TOKEN already present in the environment variables. I pushed a fix
