### ISSUE TITLE
dev mode network ledger missing wasm

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#933]
the change from #862 broke the `ANOMA_DEV=true` built node network initialization, which now needs to be copied into the network configuration created on start-up

**Comment by Anonyma** [comment]
I am getting this error on v0.5.0

I have to copy the `wasm` folder from the base project (`anoma`) into `.anoma/anoma-chain-name` for it to work

**Comment by tzemanovic** [comment]
> I am getting this error on v0.5.0
> 
> I have to copy the `wasm` folder from the base project (`anoma`) into `.anoma/anoma-chain-name` for it to work

The chain ID for dev-mode is `anoma-devchain.000000000000000`, but dev-mode build is setup to load the wasm files directly from the root `wasm` folder. The ledger should be able to download the pre-build wasm files (when the ledger starts-up, you should see e.g. `INFO anoma_apps::wasm_loader: Downloading WASM https://heliax-anoma-wasm-v1.s3.eu-west-1.amazonaws.com/vp_testnet_faucet.cdc7d2c6118c3f4909c700a63b97f9c734c463ac32cb30164737a2d85d6ee873.wasm...`). Alternatively, you can build them yourself with e.g. `make build-wasm-scripts` or `make build-wasm-scripts-docker`.

**Comment by james-chf** [comment]
I also had to copy the `wasm` folder into `.anoma/anoma-devchain.000000000000000`, after encountering this error while following the docs (specifically [this part](https://docs.anoma.network/v0.2.0/user-guide/ledger.html#-initialize-an-account) where you are initializing the account):

```
anoma client init-account \
  --alias my-new-acc \
  --public-key my-key \
  --source my-key
2022-04-05T09:58:50.497867Z  INFO anoma_apps::cli::context: Chain ID: anoma-devchain.000000000000000
Enter decryption password: 
Can't find checksums at .anoma/anoma-devchain.000000000000000/wasm/checksums.json
```

This is for a new ledger that was being run using `ANOMA_DEV=true anoma ledger`, maybe we could document to copy the `wasm/` directory to the chain directory when running a local development node or automate somehow?
