### ISSUE TITLE
error when creating a wallet

### ISSUE THREAD

**Issue by Artemiy-data** [anoma/anoma#934]
anoma wallet key gen
No wallet found at ".anoma/anoma-testnet-1.2.bf0181d9f7e0/wallet.toml". Creating a new one.
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: apps/src/lib/config/genesis.rs:494

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by tzemanovic** [comment]
the wallet is chain-specific, so doesn't work without having network configured (the ux could be better but it's not a high prio for now)
